# Generated by rust2rpm 27
%bcond check 1

%global crate rpm-builder

Name:           rpm-builder
Version:        0.2.0
Release:        %autorelease
Summary:        Simple Rust CLI utility for creating simple RPMs

License:        Apache-2.0
URL:            https://crates.io/crates/rpm-builder
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A simple Rust CLI utility for creating simple RPMs.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
License:        Apache-2.0

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/rpm-builder

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
